### PR TITLE
second commit

### PR DESCRIPTION
**Pull request by Nchedubem**
please kindly review my work
@Promise-J
@ChidiPatrick

Group A

### CODE REVIEW

**Review by promise-J — CHANGES_REQUESTED** [review]
To start with, I am 100% convinced that you copied this. Personally, I don't have an issue copying a portfolio from else where, however, I feel you didn't even copy it well. Have you viewed the site at all?

First, The "Developer" in the "I am a web developer" is not having a good color choice and then the site is not generally responsive. You have to make the site look well. Many elements are improperly over-lapping each other. Please improve the interface and get back to me.

**Review by promise-J — CHANGES_REQUESTED** [review]
Take away the age and the language
give the footer a good padding. The text seems to be closely packed to the footer.

**Review by promise-J — CHANGES_REQUESTED** [review]
Take away the age and the language
give the footer a good padding. The text seems to be closely packed to the footer.

**Comment by Nchedubem** [comment]
Please review l have done the correction
Thanks

**Pull request merged**
